namespace: nleiva
description: Capirca Collection for Ansible.
homepage: "https://github.com/nleiva/inventory"
name: inventory
version: 1.0.0
readme: "README.md"
authors:
    - Nicolas Leiva (https://github.com/nleiva)
license:
    - "GPL-3.0"
tags:
    - demo
    - collection
repository: "https://github.com/nleiva/inventory"